### ISSUE TITLE
Empty and Null Arrays of simple scalars are not handled correctly by ParquetConvert,*

### ISSUE THREAD

**Issue by GKrivosheev-rms** [aloneguid/parquet-dotnet#106]
**Version:** Parquet.Net v 3.7.7, v3.8.6

**Runtime Version:** .Net Framework 2.1 Standard & .NET Core 3.0

**OS:** Windows and AWS Linux.

#### Expected behavior

Expected: Empty and null arrays in a class should be (de)serialized correctly.

#### Actual behavior

Null and empty arrays cause crashes and corrupted data.

### Steps to reproduce the behavior

1.  Serialize or de-serialize classes that have arrays of simple types that contain either empty or null arrays.

#### Code snippet reproducing the behavior

```csharp
        class Row
        {
            public int Cell { get; set; }
            public int[] Cells { get; set; }
        }

        [Fact]
        public void ParquetConvertTest()
        {
            var rows = new List<Row> {
          //  { new Row(){ Cells = null} } ,  -- crashes on serialization if uncommented
           //      at Parquet.Serialization.Values.ClrBridge.BuildColumn(DataField field, Array classInstances, Int32 classInstancesCount)
           //    at Parquet.ParquetConvert.<>c__DisplayClass0_0`1.<Serialize>b__0(DataField df)
           //    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
    
                { new Row(){ Cells = new int[]{ 1, 2 }, Cell=1  } },
                { new Row(){ Cells = new int[0], Cell=2  } },
                { new Row(){ Cells = new int[]{ 3, 2 }, Cell=3  } },
                { new Row(){ Cells = new int[]{ 4, 2 }, Cell=4  } },
                { new Row(){ Cells = new int[0], Cell=5  } },
                { new Row(){ Cells = new int[]{ 6, 2 }, Cell=6  } }, -- Cell and Cells are not correctly aligned
            };

            ParquetConvert.Serialize(rows, "test.parquet");
            using FileStream stream = File.OpenRead("test.parquet");
            Row[] outRows = ParquetConvert.Deserialize<Row>(stream);

           // Errors:  
           // - Empty array becomes null arrays.  
           //  - Columns are misaligned between rows:
           // Actual: outRows[0] !=null and outRows[5] ==null.=, while Cell values are correct.
            Assert.Equal(rows, outRows);
        }
```

**Comment by GKrivosheev-rms** [comment]
As a matter of fact I'd be happy to find ANY way to read and write classes that contain null or empty arrays of primitive types, not just ParquetConvert...

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.

**Comment by GKrivosheev-rms** [comment]
Had to switch to Google .NET Parquet client over this issue but the way...

**Comment by aloneguid** [comment]
Welcome to open-source where no one owes you anything :) Glad it worked out.
