### ISSUE TITLE
Expected System.DateTimeOffset but found System.DateTime 

### ISSUE THREAD

**Issue by cornelcocioaba** [aloneguid/parquet-dotnet#124]
**Version:** Parquet.Net v3.9.0

**Runtime Version:**  .Net Core 3.1

**OS:** Windows

#### Expected behavior

Using DateTime type should work

#### Actual behavior

An exception is thrown because Parquet.Net tries to convert a DateTime to a DateTimeOffset:
```diff
! System.ArgumentException : expected System.DateTimeOffset but found System.DateTime
``` 
### Steps to reproduce the behavior
Run the tests bellow.

#### Code snippet reproducing the behavior

```csharp
      [Fact]
      public void Flat_add_valid_DateTime_row_succeeds()
      {
         var table = new Table(new Schema(new DataField<DateTime>("timestamp")));
         table.Add(new Row(DateTime.Now));
      }
```

**Comment by shawnjones253** [comment]
Same issue using the column-based API:
```
System.InvalidCastException: Unable to cast object of type 'System.DateTime[]' to type 'System.DateTimeOffset[]'.
   at Parquet.Data.ArrayView.GetValuesAndReturnArray[T](DataColumnStatistics statistics, IEqualityComparer`1 equalityComparer, IComparer`1 comparer)+MoveNext()
   at Parquet.Data.Concrete.DateTimeOffsetDataTypeHandler.WriteAsInt96(BinaryWriter writer, ArrayView values, DataColumnStatistics dataColumnStatistics)
   at Parquet.Data.Concrete.DateTimeOffsetDataTypeHandler.Write(SchemaElement tse, BinaryWriter writer, ArrayView values, DataColumnStatistics statistics)
   at Parquet.File.DataColumnWriter.WriteColumn(DataColumn column, SchemaElement tse, IDataTypeHandler dataTypeHandler, Int32 maxRepetitionLevel, Int32 maxDefinitionLevel)
   at Parquet.File.DataColumnWriter.Write(List`1 path, DataColumn column, IDataTypeHandler dataTypeHandler)
   at Parquet.ParquetRowGroupWriter.WriteColumn(DataColumn column)
   at ConsoleApp1.Program.Main(String[] args)
```

repro:
```
var dtColumn = new DataColumn(
                new DataField<DateTime>("dt"),
                new DateTime[] { DateTime.UtcNow.AddDays(-1), DateTime.UtcNow });
            
            var schema = new Schema(dtColumn.Field);

            using (Stream stream = new MemoryStream())
            {
                using (var parquetWriter = new ParquetWriter(schema, stream))
                {
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        groupWriter.WriteColumn(dtColumn);
                    }
                }
            }
```

**Comment by aloneguid** [comment]
you can use DTO as a workaround. Feel free to raise a PR and fix it.
