### ISSUE TITLE
Create parquet schema a struct that contains a list of structs

### ISSUE THREAD

**Issue by mat-berna** [aloneguid/parquet-dotnet#140]
**Version:** Parquet.Net v3.9.0

**Runtime Version:** .Net Core v3.1

**OS:** Windows 10

#### Expected behavior

As you can see from the code below, I want to create a struct with a list field that contains structs.

#### Actual behavior

I have an exception when I execute the code below:

```
at Parquet.Data.Rows.RowValidator.ValidateList(ListField lf, Object value)
at Parquet.Data.Rows.RowValidator.Validate(Row row, IReadOnlyList`1 fields)
at Parquet.Data.Rows.RowValidator.Validate(Row row, IReadOnlyList`1 fields)
at Parquet.Data.Rows.Table.Add(Row item)

simple list must be a collection, but found System.Int32
```

### Steps to reproduce the behavior

1. Execute the unit test that you can find below.

#### Code snippet reproducing the behavior

```csharp
[Fact]
public void Create_parquet_with_struct_list_of_struct()
{
    try
    {
        var newFilePath = $"{new Random().Next(1, 1000)}.parquet";

        var schema = new Schema
        (
            new StructField("root",
              new ListField("structs",
                new StructField("mystruct",
                 new DataField<long>("id"),
                 new DataField<string>("name"))
              )
            )
        );

        var inputRow = 
            new Row(
                new Row(
                    new List<Row>
                    {
                        new Row(1, "Joe"),
                        new Row(2, "Bloggs")
                    }
                )
            );

        var table = new Table(schema);
        table.Add(inputRow); // exception!!

        // code to create file...
    }
    catch
    {
        Assert.True(false);
    }
}
```

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.
