### ISSUE TITLE
How to create Parquet.Data.DataColumn

### ISSUE THREAD

**Issue by dburtsev** [aloneguid/parquet-dotnet#153]
**Runtime Version:** .Net Framework v, .Net Core v etc.
.NET 6.0
**OS:** Windows/Linux/MacOSX v etc.
Winwows 10
#### Expected behavior
write to file
#### Actual behavior
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Parquet.Data.DataColumn.CalculateRowCount()
   at Parquet.ParquetRowGroupWriter.WriteColumn(DataColumn column)
   at tesrwrite.Program.Main(String[] args) in C:\Work\Parquet\testwrite\Program.cs:line 60

#### Code snippet reproducing the behavior

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using System.IO;
using Parquet; // dotnet add package Parquet.Net --version 3.9.1
using Parquet.Data;

namespace tesrwrite
{
    class Program
    {
        static void Main(string[] args)
        {
            var numArray = new int?[] { };
            var singlArray = new Single?[] { };
            System.Data.DataTable dt = new System.Data.DataTable();
            System.Data.DataColumn column;
            DataRow row;
            column = new System.Data.DataColumn("intclmn", System.Type.GetType("System.Int32"));
            dt.Columns.Add(column);
            column = new System.Data.DataColumn("singlclmn", System.Type.GetType("System.Single"));
            dt.Columns.Add(column);
            row = dt.NewRow();
            row["intclmn"] = 1;
            row["singlclmn"] = 1.1;
            dt.Rows.Add(row);

            Parquet.Data.DataField[]df = new Parquet.Data.DataField[dt.Columns.Count];
            for (int i = 0; i < dt.Columns.Count; i++)
            {
                switch (System.Type.GetTypeCode(dt.Columns[i].DataType)) {
                    case TypeCode.Int32: df[i] = new Parquet.Data.DataField(dt.Columns[i].ColumnName, DataType.Int32, hasNulls: true, isArray: true); break;
                    case TypeCode.Single: df[i] = new Parquet.Data.DataField(dt.Columns[i].ColumnName, DataType.Float, hasNulls: true, isArray: true); break;
                    default: Console.WriteLine("DataType issue - {0}, {1}", dt.Columns[i].ColumnName, dt.Columns[i].DataType.Name); break;
                }
            }
            var schema = new Schema(df);
            using (System.IO.Stream fileStream = System.IO.File.Create("C:\\Work\\Parquet\\test.parquet"))
            {
                using (var parquetWriter = new ParquetWriter(schema, fileStream))
                {
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        for (int i = 0; i < df.Length; i++)
                        {
                            Parquet.Data.DataColumn clmn = null;
                            Console.WriteLine(df[i].Name + " " + df[i].DataType.ToString());
                            switch (df[i].DataType)
                            {
                                case Parquet.Data.DataType.Int32 : { numArray = dt.AsEnumerable().Select(d => d.Field<int?>(df[i].Name)).ToArray(); clmn = new Parquet.Data.DataColumn(df[i], numArray); break; }
                                case Parquet.Data.DataType.Float: { singlArray = dt.AsEnumerable().Select(d => d.Field<Single?>(df[i].Name)).ToArray(); clmn = new Parquet.Data.DataColumn(df[i], singlArray); break; }
                                default: Console.WriteLine("Not found "+ df[i].DataType.ToString()); break;
                            }    
                            if (clmn is null) {
                                Console.WriteLine("column is null");
                            }
                            groupWriter.WriteColumn(clmn);
                        }
                    }
                }
            }

        }
    }
}
```

**Comment by houseofcat** [comment]
I am going to say this as gently as possible.

1. Writing to file works.
2. Breakpoint your own code on line `groupWriter.WriteColumn(clmn);` and look at `clmn` value and what is stored there.

A word of caution, based on your last issue (float and Single), you are also learning C#. This is awesome. It's my absolute favorite language and tech stack. However, I suggest you learn the basics before opening an issue every time you don't get things to work. Your use of his Issues board strikes me - and I am trying to be as polite as possible - rude. The author is not responsible for your C# learning process nor have they volunteered themselves to do so... **_otherwise I wouldn't step up and speak to it_**. I have only stuck my nose into your business to help @aloneguid because he appears to be very busy and I have a rather large Parquet.Net issue myself.

I know I sound harsh and snobbish. I have been in your shoes before myself, so I will attempt to guide you based on your above code.

The exception is legitimate.

Let's break it down.
1. The exception is valid.
2. Therefore, you have a bug in your code snippet.
3. DataColumn must be null.
4. You assign DataColumn to null.
5. You have 3 cases in your switch, of the 3, one results in a still null DataColumn (the default case).
6. You write to console Column is null.
7. You then write column regardless of it being `null` or not because you do not have an `else `statement to go with your `if` statement.

^ Is line 7 the bug?

**Comment by dburtsev** [comment]
Hi @houseofcat 
I clean up my code
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
//using System.Threading.Tasks;
using System.Data;
using System.IO;
using Parquet; // dotnet add package Parquet.Net --version 3.9.1
using Parquet.Data;

namespace testwrite
{
    class Program
    {
        static void Main(string[] args)
        {
            var numArray = new int?[] { };
            var singlArray = new Single?[] { };
            System.Data.DataTable dt = new System.Data.DataTable();
            System.Data.DataColumn column;
            DataRow row;
            column = new System.Data.DataColumn("intclmn", typeof(Int32));
            dt.Columns.Add(column);
            row = dt.NewRow();
            row["intclmn"] = 9;
            dt.Rows.Add(row);

            Parquet.Data.DataField[]df = new Parquet.Data.DataField[dt.Columns.Count];
            for (int i = 0; i < dt.Columns.Count; i++)
            {
                switch (System.Type.GetTypeCode(dt.Columns[i].DataType)) {
                    case TypeCode.Int32: df[i] = new Parquet.Data.DataField(dt.Columns[i].ColumnName, DataType.Int32, hasNulls: true, isArray: true); break;
                    default: Console.WriteLine("DataType issue - {0}, {1}", dt.Columns[i].ColumnName, dt.Columns[i].DataType.Name); break;
                }
            }
            var schema = new Schema(df);
            using (System.IO.Stream fileStream = System.IO.File.Create("C:\\Work\\Parquet\\test.parquet"))
            {
                using (var parquetWriter = new ParquetWriter(schema, fileStream))
                {
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        for (int i = 0; i < df.Length; i++)
                        {
                            Parquet.Data.DataColumn clmn = null;
                            switch (df[i].DataType)
                            {
                                case Parquet.Data.DataType.Int32 : { 
                                    numArray = dt.AsEnumerable().Select(d => d.Field<int?>(dt.Columns[i].ColumnName)).ToArray(); 
                                    clmn = new Parquet.Data.DataColumn(df[i], numArray); break; }
                                default: Console.WriteLine("Not found "+ df[i].DataType.ToString()); break;
                            }    
                            if (clmn is null) {
                                Console.WriteLine("DataColumn is null"); }
                            else {
                                Console.WriteLine("DataColumn is NOT null");
                                Console.WriteLine("Array count is "  + numArray.Count().ToString() + " first value is " + numArray[0].ToString());
                                Console.WriteLine("DataColumn field name is " + clmn.Field.Name + ", type is " + clmn.Field.ClrType.ToString() + ", Repetitions is " + clmn.HasRepetitions.ToString());
                                groupWriter.WriteColumn(clmn);
                                 }                               
                        }
                    }
                }
            }

        }
    }
}
```
This is the output:
DataColumn is NOT null
Array count is 1 first value is 9
DataColumn field name is intclmn, type is System.Int32, Repetitions is False
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Parquet.Data.DataColumn.CalculateRowCount()
   at Parquet.ParquetRowGroupWriter.WriteColumn(DataColumn column)
   at testwrite.Program.Main(String[] args) in C:\Work\Parquet\testwrite\Program.cs:line 59

**Comment by houseofcat** [comment]
I see the issue you are passing in an array of single `int?` but have told it the schema to expect an array of arrays (isArray: true). If it is a column of `int?` you create a DataColumn with a `int? []`. If it is a column of int?[] on every line, you pass in `int? [] []` (an array of arrays) and tell the schema it's array type.

Either your example is wrong, or the schema is wrong.
`new Parquet.Data.DataField(dt.Columns[i].ColumnName, DataType.Int32, hasNulls: true, isArray: true);`

should be `isArray: false`.

**Comment by dburtsev** [comment]
Works.
Thanks
