### ISSUE TITLE
Empty List of Structs Not Encoding Properly

### ISSUE THREAD

**Issue by n00j** [aloneguid/parquet-dotnet#170]
**Version:** Parquet.Net v3.9.1

**Runtime Version:**.NET 6.0

**OS:** Windows

#### Expected behavior

When I generate a parquet file with Parquet.net with a empty List of Structs, it cannot be read by pyarrow's implementation

```
Schema schema = new Schema(
            new DataField<int>("Id"),
            new ListField(
                "ListField",
                new StructField(
                    "StructField",
                    new DataField<int>("Field1"),
                    new DataField<int>("Field2"))));

    table.Add(
        1,
        new Row[] { });
```

results in pyarrow erroring out with `File(bin/Debug/net6.0/testfile.parquet) cannot be read as parquet.`

#### Actual behavior

I believe the files encoded with Parquet.net should be able to be read by pyarrow. I'm not very familiar with the parquet format, so its possible pyarrow is not encoding/decoding it correctly either.

### Steps to reproduce the behavior

I have attached a zip file. It contains a test project with python scripts which use pyarrow to demonstrate the issue:
[parquetwritetest.zip](https://github.com/aloneguid/parquet-dotnet/files/8928812/parquetwritetest.zip)

1. Run the project it will generate a file `bin/Debug/net6.0/testfile.parquet`  
[testfile.zip](https://github.com/aloneguid/parquet-dotnet/files/8928864/testfile.zip)

2. Run (using python3.8) `python pyarrow_test.py` and it will generate `testfilepython.parquet`  
[testfilepython.zip](https://github.com/aloneguid/parquet-dotnet/files/8928866/testfilepython.zip)

3. You can then use `python pyarrow_readschema.py pyarrow_readschema.py` to show the schema for pyarrow encoded file:
```
<pyarrow._parquet.FileMetaData object at 0x0000017E7AEA9450>
  created_by: parquet-cpp-arrow version 8.0.0
  num_columns: 3
  num_rows: 1
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 864
<pyarrow._parquet.ParquetSchema object at 0x0000017E7FB6C7C0>
required group field_id=-1 schema {
  optional int64 field_id=-1 Id;
  optional group field_id=-1 ListField (List) {
    repeated group field_id=-1 list {
      optional group field_id=-1 item {
        optional int32 field_id=-1 Field1;
        optional int32 field_id=-1 Field2;
      }
    }
  }
}
```
4. You can use the same script to show the Parquet.NET encoded schema (which matches the python script) `python pyarrow_readschema.py bin/Debug/net6.0/testfile.parquet`
```
<pyarrow._parquet.FileMetaData object at 0x00000270F95692C0>
  created_by: Parquet.Net version %Version% (build %Git.LongCommitHash%)
  num_columns: 3
  num_rows: 1
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 403
<pyarrow._parquet.ParquetSchema object at 0x00000270FAE2C980>
required group field_id=-1 root {
  required int32 field_id=-1 Id;
  optional group field_id=-1 ListField (List) {
    repeated group field_id=-1 list {
      optional group field_id=-1 StructField {
        required int32 field_id=-1 Field1;
        required int32 field_id=-1 Field2;
      }
    }
  }
}
```
You will notice the serialized_size is significantly different.

5. You can then try to read the files:
pyarrow generated file:
```
python pyarrow_readfile.py testfilepython.parquet
pyarrow.Table
Id: int64
ListField: list<item: struct<Field1: int32, Field2: int32>>
  child 0, item: struct<Field1: int32, Field2: int32>
      child 0, Field1: int32
      child 1, Field2: int32
----
Id: [[1]]
ListField: [[    -- is_valid: all not null
    -- child 0 type: int32
[]
    -- child 1 type: int32
[]]]
```

Parquet.NET File
```
python pyarrow_readfile.py bin/Debug/net6.0/testfile.parquet
Traceback (most recent call last):
  File "pyarrow_readfile.py", line 6, in <module>
    print(parquet_file.read_row_group(0))
  File "C:\Python38\lib\site-packages\pyarrow\parquet\__init__.py", line 410, in read_row_group
    return self.reader.read_row_group(i, column_indices=column_indices,
  File "pyarrow\_parquet.pyx", line 1320, in pyarrow._parquet.ParquetReader.read_row_group
  File "pyarrow\_parquet.pyx", line 1345, in pyarrow._parquet.ParquetReader.read_row_groups
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Column 1 named ListField expected length 1 but got length 0
```

#### Code snippet reproducing the behavior

See code + parquet files attached

I would be happen to contribute to fix this if you believe this is an issue and I haven't done anything wrong.

**Comment by aloneguid** [comment]
closing due to inactivity
