### ISSUE TITLE
Serialisation broken in 3.10.0 and 4.0.0 when a DataField's propertyName is null

### ISSUE THREAD

**Issue by El-Gor-do** [aloneguid/parquet-dotnet#179]
**Version:** Parquet.Net v3.10.0 and v4.0.0

**Runtime Version:** .Net 6.0

**OS:** Windows

#### Expected behavior

ParquetConvert.Serialize(...) should succeed if a schema's DataField is constructed with a null propertyName.

#### Actual behavior

ParquetConvert.Serialize(...) throws ArgumentNullException.

#### Code snippet reproducing the behavior

Sample console app using Parquet 3.9.1 that successfully serialises.
```
using System.Collections.Generic;
using System.IO;

using Parquet;
using Parquet.Data;

namespace TestParquet
{
    internal class Program
    {
        public class TestClass
        {
            public int Int32Value { get; set; }

            public static Schema CreateSchema()
            {
                return new Schema(
                    new DataField(nameof(Int32Value), DataType.Int32, false, false)
                    );
            }
        }

        static void Main()
        {
            List<TestClass> items = new List<TestClass>()
            {
                new TestClass() { Int32Value = 1 },
                new TestClass() { Int32Value = 2 },
            };

            string filePath = Path.GetTempFileName();
            const int bufferSize = 16384;
            using (FileStream stream = new FileStream(filePath, FileMode.Create, FileAccess.ReadWrite, FileShare.Read, bufferSize, FileOptions.DeleteOnClose))
            {
                Schema schema = TestClass.CreateSchema();
                CompressionMethod compressionMethod = CompressionMethod.Gzip;
                const int rowGroupSize = 5000;

                schema = ParquetConvert.Serialize(items, stream, schema, compressionMethod, rowGroupSize);
            }
        }
    }
}
```

Update the Parquet.Net reference to 3.10.0 and run again. The last line `schema = ParquetConvert.Serialize(items, stream, schema, compressionMethod, rowGroupSize);` now throws
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at System.Reflection.TypeInfo.GetDeclaredProperty(String name)
   at Parquet.Serialization.Values.MSILGenerator.GenerateCollector(ILGenerator il, Type classType, DataField f, MethodInfo getValueMethod, MethodInfo addToListMethod, MethodInfo addRepLevelMethod, TypeConversion conversion)
   at Parquet.Serialization.Values.MSILGenerator.GenerateCollector(Type classType, DataField field)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Parquet.Serialization.Values.ClrBridge.BuildColumn(DataField field, Array classInstances, Int32 classInstancesCount)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Parquet.ParquetConvert.Serialize[T](IEnumerable`1 objectInstances, Stream destination, Schema schema, CompressionMethod compressionMethod, Int32 rowGroupSize, Boolean append)
   at TestParquet.Program.Main() in D:\dev\bugs\Parquet4SerialisationFailure\TestParquet\Program.cs:line 40
```

The bug is caused by `new DataField(nameof(Int32Value), DataType.Int32, false, false)` using the default `propertyName` value `null`. If `propertyName` is explicitly set to a non-null value using `new DataField(nameof(Int32Value), DataType.Int32, false, false, nameof(Int32Value))` then serialisation is successful.

Parquet.Net 4.0.0 has the same bug and is also fixed by constructing a `DataField` with a non-null `propertyName`. Sample code using 4.0.0's new async API:
```
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

using Parquet;
using Parquet.Data;

namespace TestParquet
{
    internal class Program
    {
        public class TestClass
        {
            public int Int32Value { get; set; }

            public static Schema CreateSchema()
            {
                return new Schema(
                    new DataField(nameof(Int32Value), DataType.Int32, false, false)
                    );
            }
        }

        static async Task Main()
        {
            List<TestClass> items = new List<TestClass>()
            {
                new TestClass() { Int32Value = 1 },
                new TestClass() { Int32Value = 2 },
            };

            string filePath = Path.GetTempFileName();
            const int bufferSize = 16384;
            using (FileStream stream = new FileStream(filePath, FileMode.Create, FileAccess.ReadWrite, FileShare.Read, bufferSize, FileOptions.DeleteOnClose))
            {
                Schema schema = TestClass.CreateSchema();
                CompressionMethod compressionMethod = CompressionMethod.Gzip;
                const int rowGroupSize = 5000;

                schema = await ParquetConvert.SerializeAsync(items, stream, schema, compressionMethod, rowGroupSize);
            }
        }
    }
}
```

**Comment by El-Gor-do** [comment]
A schema containing fields instantiated using `DataField<T>`,  `DateTimeDataField` and `DecimalDataField` constructors also cause an ArgumentNullException on ParquetConvert.Serialize because none of these 3 constructors call the base `DataField` constructor with a `propertyName` argument.

**Comment by El-Gor-do** [comment]
Instead of explicitly constructing a schema using `DataField`s, if `TestClass`'s properties are annotated with `ParquetColumnAttribute`  like this:
```
    public class TestClass
    {
        [ParquetColumn(Name = nameof(DateTimeOffsetValue), DateTimeFormat = DateTimeFormat.Date)]
        public DateTimeOffset DateTimeOffsetValue { get; set; }

        [ParquetColumn(Name = nameof(DecimalValue), DecimalPrecision = 38, DecimalScale = 18)]
        public decimal DecimalValue { get; set; }
        
        [ParquetColumn(Name = nameof(Int32Value))]
        public int Int32Value { get; set; }
    }
```

then ParquetConvert.SerializeAsync doesn't need to be passed a schema and serialisation succeeds:
```
Schema schema = await ParquetConvert.SerializeAsync(items, stream, compressionMethod: compressionMethod, rowGroupSize: rowGroupSize);
```
