### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by Cinchoo** [aloneguid/parquet-dotnet#210]
Noticed file is failing to read successfully after v4.1.0.

Same file, I can successfully load in prior versions. I believe something got to so with compression library.
See below stack trace. Let me know if you need any additional information. thanks.

Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at IronCompress.Iron.compress(Boolean, Int32, Byte*, Int32, Byte*, Int32*)
at IronCompress.Iron.compress(Boolean, Int32, Byte*, Int32, Byte*, Int32*)
at IronCompress.Iron.CompressOrDecompress(Boolean, IronCompress.Codec, System.ReadOnlySpan1<Byte>, System.Nullable1)
at IronCompress.Iron.Decompress(IronCompress.Codec, System.ReadOnlySpan1<Byte>, System.Nullable1)
at Parquet.File.Compressor.Decompress(Parquet.CompressionMethod, System.ReadOnlySpan1<Byte>, Int32) at Parquet.File.DataColumnReader+<ReadPageData>d__13.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Parquet.File.DataColumnReader+<ReadPageData>d__13, Parquet, Version=4.0.0.0, Culture=neutral, PublicKeyToken=d380b3dee6d01926]].ExecutionContextCallback(System.Object) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Parquet.File.DataColumnReader+<ReadPageData>d__13, Parquet, Version=4.0.0.0, Culture=neutral, PublicKeyToken=d380b3dee6d01926]].MoveNext(System.Threading.Thread) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Parquet.File.DataColumnReader+d__13, Parquet, Version=4.0.0.0, Culture=neutral, PublicKeyToken=d380b3dee6d01926]].ExecuteFromThreadPool(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by aloneguid** [comment]
Cannot reproduce
