### ISSUE TITLE
Cannot parse Parquet statistics when trying to read files using Spark

### ISSUE THREAD

**Issue by itayfisz** [aloneguid/parquet-dotnet#261]
Hey,
I tried to use Spark 3.2 to read parquet files written using Parquet.Net. The Spark job took very long, so I looked into Spark logs and saw this:

**Ignoring statistics because created_by could not be parsed (see PARQUET-251): Parquet.Net v4.4.6
org.apache.parquet.VersionParser$VersionParseException: Could not parse created_by: Parquet.Net v4.4.6 using format: (.*?)\s+version\s*(?:([^(]*?)\s*(?:\(\s*build\s*([^)]*?)\s*\))?)?**

Any idea what is this "created_by", and how can it be changed?

Thanks!

Here is the full error:
```
23/02/14 12:54:21 WARN CorruptStatistics [Executor task launch worker for task 2.0 in stage 9.0 (TID 118)]: Ignoring statistics because created_by could not be parsed (see PARQUET-251): Parquet.Net v4.4.6
org.apache.parquet.VersionParser$VersionParseException: Could not parse created_by: Parquet.Net v4.4.6 using format: (.*?)\s+version\s*(?:([^(]*?)\s*(?:\(\s*build\s*([^)]*?)\s*\))?)?
	at org.apache.parquet.VersionParser.parse(VersionParser.java:109)
	at org.apache.parquet.CorruptStatistics.shouldIgnoreStatistics(CorruptStatistics.java:72)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetStatisticsInternal(ParquetMetadataConverter.java:811)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetStatistics(ParquetMetadataConverter.java:831)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.buildColumnChunkMetaData(ParquetMetadataConverter.java:1462)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetMetadata(ParquetMetadataConverter.java:1535)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1450)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:582)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:527)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:521)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:497)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReader$$anon$1.call(ParquetMetadataCacheReader.scala:116)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReader$$anon$1.call(ParquetMetadataCacheReader.scala:114)
	at org.sparkproject.guava.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
	at org.sparkproject.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at org.sparkproject.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at org.sparkproject.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at org.sparkproject.guava.cache.LocalCache$Segment.get(LocalCache.java:2257)
	at org.sparkproject.guava.cache.LocalCache.get(LocalCache.java:4000)
	at org.sparkproject.guava.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReader$.getFooterFromCache(ParquetMetadataCacheReader.scala:114)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReader$.$anonfun$getFooter$3(ParquetMetadataCacheReader.scala:91)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReader$.$anonfun$getFooter$2(ParquetMetadataCacheReader.scala:91)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReaderSource.runWithTimerAndRecord(ParquetMetadataCacheReaderSource.scala:64)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReader$.getFooter(ParquetMetadataCacheReader.scala:91)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetMetadataCacheReader$.getFooter(ParquetMetadataCacheReader.scala:78)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.footerFileMetaData$lzycompute$1(ParquetFileFormat.scala:336)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.footerFileMetaData$1(ParquetFileFormat.scala:335)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.$anonfun$buildReaderWithPartitionValues$2(ParquetFileFormat.scala:338)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:146)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:208)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:123)
	at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.hasNext(DataSourceScanExec.scala:543)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.columnartorow_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:763)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:386)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:905)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:905)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:57)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by itayfisz** [comment]
I would assume, by looking at the regex in the exception, that the created_by string should be changed to "Parquet.Net version 4.4.6" (instead of Parquet.Net v4.4.6)...?

https://github.com/aloneguid/parquet-dotnet/blob/0911415847678991222044eec92841f2d1399a76/src/Parquet/File/ThriftFooter.cs

I wonder why Spark cares so much about this field in order to parse the file statistics.

**Comment by aloneguid** [comment]
Yeah this is weird. From thrift spec:

```
  /** String for application that wrote this file.  This should be in the format
   * <Application> version <App Version> (build <App Build Hash>).
   * e.g. impala version 1.0 (build 6cf94d29b2b7115df4de2c06e2ab4326d721eb55)
   **/
  6: optional string created_by
```

key words are "should" and "optional".

**Comment by itayfisz** [comment]
> Yeah this is weird. From thrift spec:
> 
> ```
>   /** String for application that wrote this file.  This should be in the format
>    * <Application> version <App Version> (build <App Build Hash>).
>    * e.g. impala version 1.0 (build 6cf94d29b2b7115df4de2c06e2ab4326d721eb55)
>    **/
>   6: optional string created_by
> ```
> 
> key words are "should" and "optional".

Wow, thanks so much for the quick fix!
Do you know when should I expect to have a new version published with this commit?

**Comment by aloneguid** [comment]
Being a nice guy I am (all inclusive (to Spark (it's so complex I think of it as a human being (apologies for LISP syntax)))) it's fixed in 4.5.1 and should be visible in nuget in a few minutes from now.

**Comment by aloneguid** [comment]
Hope it's working for you. Feel free to reopen if not.

**Comment by itayfisz** [comment]
> Hope it's working for you. Feel free to reopen if not.

Yes, that seems to work now. Thanks again!
