### ISSUE TITLE
[BUG]: .netstandard 2.0 compatibility (maybe only when using matlab)

### ISSUE THREAD

**Issue by mithom** [aloneguid/parquet-dotnet#275]
### Library Version

4.5.4

### OS

windows 11

### OS Architecture

64 bit

### How to reproduce?

sorry to list this as a bug here, but i am out of idea's.

your nugget package says it supports .net standard 2.0. I am working in .NET Framework 4.7.2, which falls under .netstanderd 2.0 if i'm not mistaken. The build goes fine, and my csproj resolve the System.Buffer dependency to 4.0.3.0 (NuGet version 4.5.1).
When i build my DLL and call the code from my MATLAB environment, for some reason i get the following erros (first is when trying to write data to a column, the second one is when i don't write anything when the parquetWriter goes out of scope and thus calls its Dispose function). For some reason it is trying to load file version 4.0.2.0 of System.Buffers when Disposing?? I've looked into the source code and this is very strange to me as i would think the package gets loaded when the ArrayPool is first used, which is with the static variable instantiation.

Using an App.config file did not resolve this issue sadly enough and i was wondering if anyone here had an idea what could cause this behavior. It is the first time i am facing such an issue that i cannot lead back to incompatible nuget requirements (as everything has the same >=4.5.1 requirement).

If you say this is not an issue of the library, you can just close/delete this ticket. I'm just desperately looking for assistance as i wasted a full day looking to resolve this issue.

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
  Source=Parquet
  StackTrace:
   at Parquet.File.PackedColumn.Dispose()
   at Parquet.File.DataColumnWriter.<WriteColumnAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Parquet.File.DataColumnWriter.<WriteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Parquet.ParquetRowGroupWriter.<WriteColumnAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SmartLabBase.Uploader.ParquetProcessor.<CreateParquetFile>d__6.MoveNext() in C:\Users\xxxx\Documents\MBE\MBE INTEGRATIONS\MBE Toolbox\MBE.Toolbox\CalcModules\SmartLab\SmartLabBase\Uploader\ParquetProcessor.cs:line 76



System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Parquet.ParquetWriter.Dispose()
   at SmartLabBase.Uploader.ParquetProcessor.<CreateParquetFile>d__6.MoveNext() in C:\Users\xxxx\Documents\MBE\MBE INTEGRATIONS\MBE Toolbox\MBE.Toolbox\CalcModules\SmartLab\SmartLabBase\Uploader\ParquetProcessor.cs:line 128
```

### Failing test

```csharp
my code is a DLL library, so it is hard to share this as it is called from a matlab environment. i can share pieces of code when requested though
```

**Comment by mithom** [comment]
i made a little project that already had the same issue, without any other dependencies (i thought it was a dependency issue)
`using Parquet;
using Parquet.Data;
using Parquet.Schema;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace test2
{
    public static class Class1
    {
        public static async Task test()
        {
            ParquetSchema schema = new ParquetSchema(new Field[] { 
                new DataField<string>("String"),
                new DataField<int>("Int"),
                new DataField<DateTime>("DateTime")
            });
            string fileName = "testFile.parquet";
            using (FileStream targetFile = File.Create(fileName))
            {
                using (ParquetWriter writer = await ParquetWriter.CreateAsync(schema, targetFile))
                {
                    using (ParquetRowGroupWriter groupWriter = writer.CreateRowGroup())
                    {
                        int[] repititionLevel = Enumerable.Repeat(0, 5).ToArray();

                        DataColumn col1 = new DataColumn((DataField)schema[0], new string[] { "0", "1", "2", "3", "4" }, repititionLevel);
                        DataColumn col2 = new DataColumn((DataField)schema[0], new int[] { 0,1,2,3,4,}, repititionLevel);
                        DataColumn col3 = new DataColumn((DataField)schema[0], new DateTime[] { DateTime.UtcNow, DateTime.UtcNow, DateTime.UtcNow, DateTime.UtcNow, DateTime.UtcNow }, repititionLevel);

                        await groupWriter.WriteColumnAsync(col1);
                        await groupWriter.WriteColumnAsync(col2);
                        await groupWriter.WriteColumnAsync(col3);
                    }
                }
            }
        }
    }
}
`

**Comment by mithom** [comment]
this is the csproj file used for the project

```<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{384C0C58-8354-4190-93A0-96AC6E31775E}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>test2</RootNamespace>
    <AssemblyName>test2</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="IronCompress, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d380b3dee6d01926, processorArchitecture=MSIL">
      <HintPath>packages\IronCompress.1.3.0\lib\netstandard2.0\IronCompress.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\Microsoft.Bcl.AsyncInterfaces.7.0.0\lib\net462\Microsoft.Bcl.AsyncInterfaces.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.IO.RecyclableMemoryStream, Version=2.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>packages\Microsoft.IO.RecyclableMemoryStream.2.3.1\lib\net462\Microsoft.IO.RecyclableMemoryStream.dll</HintPath>
    </Reference>
    <Reference Include="Parquet, Version=4.0.0.0, Culture=neutral, PublicKeyToken=d380b3dee6d01926, processorArchitecture=MSIL">
      <HintPath>packages\Parquet.Net.4.5.4\lib\netstandard2.0\Parquet.dll</HintPath>
    </Reference>
    <Reference Include="Snappier, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a1b25124e6e13a3a, processorArchitecture=MSIL">
      <HintPath>packages\Snappier.1.0.0\lib\netstandard2.0\Snappier.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Buffers.4.5.1\lib\net461\System.Buffers.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Memory.4.5.5\lib\net461\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics" />
    <Reference Include="System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>packages\System.Numerics.Vectors.4.5.0\lib\net46\System.Numerics.Vectors.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>packages\System.Runtime.CompilerServices.Unsafe.6.0.0\lib\net461\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Encodings.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Text.Encodings.Web.7.0.0\lib\net462\System.Text.Encodings.Web.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Text.Json.7.0.2\lib\net462\System.Text.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Threading.Tasks.Extensions.4.5.4\lib\net461\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.ValueTuple.4.5.0\lib\net47\System.ValueTuple.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Class1.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>```

**Comment by mithom** [comment]
running this script in a Console Application instead of in matlab results in an even faster error:

https://prnt.sc/ZNnKCTBe7mHO

**Comment by mithom** [comment]
apparently the test script works when copying over the assembly redirects from the library class to the console application, but this does not seem to be affecting matlab :(

**Comment by mithom** [comment]
it was a matlab issue, writing my own assembly binding redirect resolver to force matlab to respect the config files resolved this for me.
