### ISSUE TITLE
[BUG]: cannot count nulls in type System.Nullable`1[System.DateTimeOffset]

### ISSUE THREAD

**Issue by tylerchessman** [aloneguid/parquet-dotnet#293]
### Library Version

4.6.2

### OS

Windows 11

### OS Architecture

64 bit

### How to reproduce?

I'm trying to use a modified version of https://github.com/dazfuller/datatable-to-parquet to write a datatable to a parquet file, but receive an error when writing a particular column:  rgw.WriteColumnAsync(new Parquet.Data.DataColumn(fields[i], valuesArray));

I've tried modifying the isNullable (in the GenerateSchema function), but it doesn't seem to make a difference.  Is there a simple fix to workaround?

The error is:
System.NotSupportedException
  HResult=0x80131515
  Message=cannot count nulls in type System.Nullable`1[System.DateTimeOffset]
  Source=Parquet
  StackTrace:
   at Parquet.Extensions.UntypedArrayExtensions.CalculateNullCountFast(Array array, Int32 offset, Int32 count)
   at Parquet.File.PackedColumn.Pack(Int32 maxDefinitionLevel, Boolean useDictionaryEncoding, Double dictionaryThreshold)
   at Parquet.File.DataColumnWriter.<WriteColumnAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Parquet.File.DataColumnWriter.<WriteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Parquet.ParquetRowGroupWriter.<WriteColumnAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by aloneguid** [comment]
Thank you for reporting this issue. However, I can't reproduce this as there is no info. Try to create a minimal reproducible code or unit test that demonstrates the problem and share it with me. This will help me to identify and fix the bug faster and more effectively.

**Comment by aloneguid** [comment]
Hey, I appreciate your effort, but I couldn't run your code because it needs some extra libraries, credentials, and infrastructure.

Can you please write a simple unit test here that shows the problem you're having? That would make it easier for me to help you out.

If that's not possible, you can try to debug it on your own machine and send a PR with a fix.

**Comment by tylerchessman** [comment]
Hello.  I'm not an advanced programmer.  I built a very small .Net core console app; other than your library, the only other thing I've added is System.Data.SqlClient (necessary to connect to the database. is a .Net Core console app).

The database is hosted in the cloud - I had asked you to email me so you could replace these 2 lines of code at the top of Program.cs - 
        const string _Pwd = "Your_Password_Here";
        const string _SvrName = "Server_Name_Here";
Once you do that, you are good to go.  Sorry, I don't know how to make it any simpler - or what a PR with a fix means.

**Comment by tylerchessman** [comment]
Just an update for anyone else who may come across this issue:  I was able to get things working; DateTime data type does need to be switched to DateTimeOffset (when creating the DataField object) - but I had to modify the sample datatable-to-parquet sample code to something like - 
{ await rgw.WriteColumnAsync(new Parquet.Data.DataColumn(fields[i], dt.AsEnumerable().Skip(startRow).Take(RowGroupSize).Select(s => s.Field<DateTime?>(dt.Columns[i].ColumnName)).ToArray<DateTime?>())); }

Interestingly, if you are pulling in a DataTimeOffest from the database, it also requires a DateTimeOffset (when creating the DataField object) - but I had to convert the actual row _values_ to a DateTime prior to writing the column.
