### ISSUE TITLE
[BUG]: Unable to deserialize Int64 using Class Serialization

### ISSUE THREAD

**Issue by nodeflux** [aloneguid/parquet-dotnet#350]
### Library Version

4.12.0

### OS

Windows 11

### OS Architecture

64 bit

### How to reproduce?

I have a sample file whose schema includes unique identifiers that are Int64. They load and display well in the online viewer.

I create a simple class whose field is only one Int64 property. I deserialize the data using:

`var data = await ParquetSerializer.DeserializeAsync<TestClass>(stream);`

I've tried all manner of signed and unsigned integers and longs, but in all cases I get an exception like:

`
Unhandled exception. System.ArgumentException: Destination is too short. (Parameter 'destination')
   at Parquet.Encodings.BitPackedEncoder.Decode8ValuesLE(Span'1 src, Span'1 dest, Int32 bitWidth)
   at Parquet.Encodings.RleBitpackedHybridEncoder.DecodeBitpacked(Int32 header, Span'1 data, Int32& dataOffset, Int32 bitWidth, Span'1 dest, Int32 maxItems)
   at Parquet.Encodings.RleBitpackedHybridEncoder.Decode(Span'1 data, Int32 bitWidth, Span'1 dest, Int32 pageSize)
   at Parquet.Encodings.RleBitpackedHybridEncoder.Decode(Span'1 s, Int32 bitWidth, Nullable'1 spanLength, Int32& usedSpanLength, Span'1 dest, Int32 pageSize)
   at Parquet.File.DataColumnReader.ReadRleDictionary(Span'1 s, Int32 maxReadCount, Span'1 dest)
   at Parquet.File.DataColumnReader.ReadColumn(Span'1 src, Encoding encoding, Int64 totalValuesInChunk, Int32 totalValuesInPage, PackedColumn pc)
   at Parquet.File.DataColumnReader.ReadDataPageV1Async(PageHeader ph, PackedColumn pc)
   at Parquet.File.DataColumnReader.ReadAsync(CancellationToken cancellationToken)
   at Parquet.Serialization.ParquetSerializer.DeserializeRowGroupAsync[T](ParquetReader reader, Int32 rgi, Assembler'1 asm, ICollection'1 result, CancellationToken cancellationToken)
   at Parquet.Serialization.ParquetSerializer.DeserializeAsync[T](Stream source, ParquetOptions options, CancellationToken cancellationToken)
   at Program.exportAndFilterBrokerInfo() in Program.cs:line 124`

**Comment by MadIdh** [comment]
Hello, I encounter the same issue on string data ... the same error appears
