### ISSUE TITLE
System.OutOfMemoryException exception obtained when writing data of ~1 KB.

### ISSUE THREAD

**Issue by srishti-agarwal** [aloneguid/parquet-dotnet#371]
### Issue description

Package Version: 4.15.0

 Attached Stack 
 
 DataSize = 1218, exp: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at Parquet.ParquetWriter.<PrepareFileAsync>d__16.MoveNext() in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/ParquetWriter.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Parquet.ParquetWriter.<CreateAsync>d__11.MoveNext() in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/ParquetWriter.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Parquet.Serialization.ParquetSerializer.<SerializeAsync>d__3`1.MoveNext() in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/Serialization/ParquetSerializer.cs:line 65

**Comment by aloneguid** [comment]
I'm afraid I can't reproduce it from the information provided.

**Comment by srishti-agarwal** [comment]
Apologies, I was about to close. Looks like a false alarm on my end.
