### ISSUE TITLE
[BUG]: ParquetSerializer.DeserializeAsync - "Not a parquet" file when using buffer with fixed size

### ISSUE THREAD

**Issue by edguer** [aloneguid/parquet-dotnet#437]
### Library Version

4.17.0

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

Write this code or similar:

```CSharp
var bytes = [some byte array];

// Using a 4096 buffer from the array pool
using var memoryStream = new MemoryStream(ArrayPool<byte>.Shared.Rent(4096));
await memoryStream.WriteAsync(bytes, 0, bytes.Length);
return await ParquetSerializer.DeserializeAsync<T>(memoryStream, ParquetOptions.ParquetOptions);
```

And you get:
```
  System.IO.IOException: not a parquet file, head: 50415231, tail: 00000000
Stack Trace: 
  ParquetActor.ValidateFileAsync()
  ParquetReader.InitialiseAsync(CancellationToken cancellationToken)
  ParquetReader.CreateAsync(Stream input, ParquetOptions parquetOptions, Boolean leaveStreamOpen, CancellationToken cancellationToken)
  ParquetSerializer.DeserializeAsync[T](Stream source, ParquetOptions options, CancellationToken cancellationToken)
```

The reason is the ValidateFileAsync method seeks the tail at the end of stream, which will always be 0 when the buffer is not filled:

https://github.com/aloneguid/parquet-dotnet/blob/9dcd02ec3e2120d31dd85ed31afc9255c2fc8f5c/src/Parquet/ParquetActor.cs#L42C50-L42C50
```CSharp
        protected async Task ValidateFileAsync() {
            _fileStream.Seek(0, SeekOrigin.Begin);
            byte[] head = await _fileStream.ReadBytesExactlyAsync(4);

            _fileStream.Seek(-4, SeekOrigin.End);
            byte[] tail = await _fileStream.ReadBytesExactlyAsync(4);

            if(!MagicBytes.SequenceEqual(head) || !MagicBytes.SequenceEqual(tail))
                throw new IOException($"not a parquet file, head: {head.ToHexString()}, tail: {tail.ToHexString()}");
        }
```

This would probably fix it:

```CSharp
            _fileStream.Seek((_fileStream.Position - 4), SeekOrigin.Begin);
            byte[] tail = await _fileStream.ReadBytesExactlyAsync(4);
```

**Comment by aloneguid** [comment]
Sounds good. Please raise a PR if that's ok.

**Comment by daz10000** [comment]
Is this code in the latest release `4.23.5` ?  I am getting the same error in a similar circumstance (arm, 64 bit).  The same file loads succesfully on a windows machine with the current version but seems to break on linux.  The file loads correctly with pandas, so I believe it is not corrupt.

```
System.AggregateException: One or more errors occurred. (not a parquet file, head: 50415231, tail: 3000880d)
 ---> System.IO.IOException: not a parquet file, head: 50415231, tail: 3000880d
   at Parquet.ParquetActor.ValidateFileAsync() in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/ParquetActor.cs:line 46
   at Parquet.ParquetReader.InitialiseAsync(CancellationToken cancellationToken) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/ParquetReader.cs:line 40
   at Parquet.ParquetReader.CreateAsync(Stream input, ParquetOptions parquetOptions, Boolean leaveStreamOpen, CancellationToken cancellationToken) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/ParquetReader.cs:line 80
   at FSI_0002.loadCompressedAlphaMS@156-3.MoveNext() inXXX :line 158
   at FSI_0002.loadCompressedAlphaMS@133.MoveNext() inXXX.fsx:line 155
   at FSI_0002.go@304.MoveNext() in XXX.fsx:line 311
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 453
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1130
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in
```
