### ISSUE TITLE
Do not try to set readonly properties when deserializing

### ISSUE THREAD

**Issue by Pragmateek** [aloneguid/parquet-dotnet#514]
### Issue description

Hello,

By default, when deserializing, Parquet.Net tries to set **readonly properties** which of course raises a LINQ Expression exception:
```
Unhandled exception. System.FieldAccessException: failed to compile 'N (System.Int32)'
 ---> System.ArgumentException: Expression must be writeable (Parameter 'left')
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at Parquet.Serialization.Dremel.FieldAssemblerCompiler`1.InjectLevel(Expression rootVar, Type rootType, Field parentField, Field[] levelFields, List`1 path)
```
How to make Parquet.Net read them when serializing and ignore them when deserializing?

Thanks in advance,

Mickael

```
using Parquet.Serialization;

using var ms = new MemoryStream();
await ParquetSerializer.SerializeAsync([new A()], ms);

ms.Seek(0, SeekOrigin.Begin);

await ParquetSerializer.DeserializeAsync<A>(ms);

class A
{
    public int N => 1;
}
```

**Comment by aloneguid** [comment]
It's a bug in caching

**Comment by Pragmateek** [comment]
Thanks for the fix.
It's working now, just had to add a field as otherwise it would have nothing to serialize.
