### ISSUE TITLE
[BUG]: Exception from ReadParquetAsDataFrameAsync()

### ISSUE THREAD

**Issue by alex-g-axion** [aloneguid/parquet-dotnet#558]
### Library Version

4.25.0

### OS

Windows 11

### OS Architecture

64 bit

### How to reproduce?

1. Generate a C# `DataFrame` ([Microsoft.Data.Analysis](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.analysis?view=ml-dotnet-preview).  The first one or two columns are string and the rest are double.  
2. Save this `DataFrame` to parquet using `ParquetExtensions.WriteAsync()` extension method.
3. Try to read the resulting parquet file via `ReadParquetAsDataFrameAsync()`.

I get the following exception:

{"don't know how to skip type 15"}	System.Exception {System.InvalidOperationException}
   at Parquet.Meta.Proto.ThriftCompactProtocolReader.SkipField(CompactType compactType)
   at Parquet.Meta.EncryptionAlgorithm.Read(ThriftCompactProtocolReader proto)
   at Parquet.Meta.FileMetaData.Read(ThriftCompactProtocolReader proto)
   at Parquet.ParquetActor.ReadMetadataAsync(CancellationToken cancellationToken)
   at Parquet.ParquetReader.InitialiseAsync(CancellationToken cancellationToken)
   at Parquet.ParquetReader.CreateAsync(Stream input, ParquetOptions parquetOptions, Boolean leaveStreamOpen, CancellationToken cancellationToken)
   at Parquet.ParquetExtensions.ReadParquetAsDataFrameAsync(Stream inputStream, CancellationToken cancellationToken)
   
 I was able to reproduce the issue with two tables that I saved in CSV form and attaching them along with the resulting invalid parquet files.

[ElectrodeMetrics.zip](https://github.com/user-attachments/files/17233962/ElectrodeMetrics.zip)

**Comment by aloneguid** [comment]
Thank you, but I cannot reproduce this, and it's unclear how those files were created. If you could provide a reproducible test or a program that would be great, then I could try to understand why it happens.
