### ISSUE TITLE
[BUG]: 32 bits stopped to work after upgrading to 5.0.0

### ISSUE THREAD

**Issue by garayx** [aloneguid/parquet-dotnet#564]
### Library Version

5.0.0

### OS

Windows

### OS Architecture

32 bit

### How to reproduce?

1. After upgrading to 5.0.0 I started to get the following exception:

```
System.DllNotFoundException: Unable to load nironcompress (X86/win-x86/). CD: C:\Work\Projects\test\Tryouts\bin\Debug\net8.0
 ---> System.DllNotFoundException: Unable to load DLL 'nironcompress' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at IronCompress.Native.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   --- End of inner exception stack trace ---
   at IronCompress.Native.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at IronCompress.Native.iron_is_supported(Int32 codec)
   at IronCompress.Iron.SupportsNative(Codec c)
   at IronCompress.Iron.Compress(Codec codec, ReadOnlySpan`1 input, Nullable`1 outputLength, CompressionLevel compressionLevel)
   at Parquet.File.Compressor.Compress(CompressionMethod method, ReadOnlySpan`1 input, CompressionLevel compressionLevel)
   at Parquet.File.DataColumnWriter.CompressAndWriteAsync(PageHeader ph, MemoryStream data, ColumnSizes cs, CancellationToken cancellationToken)
   at Parquet.File.DataColumnWriter.WriteColumnAsync(ColumnChunk chunk, DataColumn column, SchemaElement tse, CancellationToken cancellationToken)
   at Parquet.File.DataColumnWriter.WriteAsync(FieldPath fullPath, DataColumn column, CancellationToken cancellationToken)
   at Parquet.ParquetRowGroupWriter.WriteColumnAsync(DataColumn column, Dictionary`2 customMetadata, CancellationToken cancellationToken)
```

2. downgrading back to Parquet.Net 4.25.0 fixes the issue

3. Seems like related to this [issue](https://github.com/aloneguid/parquet-dotnet/issues/229) reported in the past.

**Comment by aloneguid** [comment]
I think v5.0.1 may fix your issue.
