### ISSUE TITLE
[BUG]: nironcompress fallback

### ISSUE THREAD

**Issue by tuseau** [aloneguid/parquet-dotnet#574]
### Library Version

5.0.2

### OS

Windows 10

### OS Architecture

64 bit

### How to reproduce?

I have a .NET Standard 2.0 C# project which write and reads parquet files to/from Azure Data Lake.
When calling the ParquetRowGroupWriter.WriteColumnAsync method or the ParquetRowGroupReader.ReadColumnAsync method, it throws an error - but only when debugging in visual studio with "CLR Exceptions" switched on in Exception Settings. This is the error:

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'nironcompress': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=IronCompress
  StackTrace:
   at IronCompress.Native.iron_ping()
   at IronCompress.Iron.get_IsNativeLibraryAvailable()
   
   
  I should point out that this error is not thrown at runtime when compiled and does not prevent the application from working.

**Comment by aloneguid** [comment]
Thanks its definitely a bug. Parquet should fall back to managed compression if native is not available, but doesn't for some reason. What is the runtime consuming .net standard library?

**Comment by tuseau** [comment]
In this case, .net 4.7.2

**Comment by aloneguid** [comment]
@tuseau end of Jan. You can try prerelease nuget today.
