### ISSUE TITLE
[BUG]: Only x out of y bytes are available

### ISSUE THREAD

**Issue by gwstroup** [aloneguid/parquet-dotnet#576]
### Library Version

5.0.2

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

1. Attempting to consume file generated by a Palantir product (backend Spark I think?) and get the following error (occurs in both the Parquet.Net package and when trying to open the file in Floor):

`System.IO.IOException: only 8317 out of 9589580 bytes are available
   at Parquet.Extensions.StreamExtensions.ReadBytesExactly(Stream s, Int32 count)
   at Parquet.Meta.Proto.ThriftCompactProtocolReader.ReadString()
   at Parquet.Meta.ColumnChunk.Read(ThriftCompactProtocolReader proto)
   at Parquet.Meta.RowGroup.Read(ThriftCompactProtocolReader proto)
   at Parquet.Meta.FileMetaData.Read(ThriftCompactProtocolReader proto)
   at Parquet.ParquetActor.ReadMetadataAsync(CancellationToken cancellationToken)
   at Parquet.ParquetReader.InitialiseAsync(CancellationToken cancellationToken)
   at Parquet.ParquetReader.CreateAsync(Stream input, ParquetOptions parquetOptions, Boolean leaveStreamOpen, CancellationToken cancellationToken)
   at Parquet.Floor.ViewModels.MainViewModel.LoadAsync(String name, Stream fileStream)`

- This was previously working, so I'm not sure if there was something that changed with the format of the parquet file. Reading the file in using: `ParquetSerializer.DeserializeAsync<HorizontalDTO>(filePath).Result.ToList();`
- I tried loading the same file using an online Parquet viewer and it successfully loaded all data

**Comment by aloneguid** [comment]
Hi, yes, Palantir is built on top of Spark. As you understand I cannot reproduce this without an actual file with only the information above. Is there something you can add?

**Comment by aloneguid** [comment]
Fixed in 5.1.0.
